Ajenti bug report
--------------------


Info | Value
----- | -----
Ajenti | 2.1.6
Platform | debian / ubuntu / elementary OS Freya
Architecture | x86_64 x86_64
Python | 2.7.6
Debug | True
Loaded plugins | 

Library | Version
------- | -------
gevent | 1.1b3
greenlet | 0.4.9
psutil | 3.3.0


    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/aj/entry.py", line 52, in handle_crash
        report = open(report_path, 'w')
    IOError: [Errno 13] Permission denied: '/root/ajenti-crash.txt'

            